%%% Template fuer TestDummy-Info-Klasse
###importedInterfaces###
	###fileWriter###
		###outputDir######componentPackagePath###test###fileSeparator######interfaceName###TestDummyInfo.java
	###endFileWriter###

	// ###interfaceName###TestDummyInfo.java generated by Generator at ###theDate###

	package ###componentPackageName###.test;



	import org.glowa.danube.simulation.*;

	import java.awt.Color;
	import java.util.*;



	public class ###interfaceName###TestDummyInfo implements ComponentInfo, java.io.Serializable
	{
  /**
   * Get identifier of this component
   */
  public String getComponentIdent()
  {
    return "###interfaceName###-TestDummy";
  }

  /**
   * Get array of imported interfaces by this component
   * A test dummy has no imported interfaces!
   */
  public String[] getImportedInterfaces()
  {
    return new String[]{};
  }

  /**
   * Get array of exported interfaces by this component
   * Exports only one interface to component being tested
   */
  public String[] getExportedInterfaces()
  {
    return new String[]
    {
		"###componentPackageName###.###interfaceName###"
    };
  }

  /**
   * Get array of result interfaces by this component
   */
  public String[] getResultInterfaces()
  {
    return new String[]
    {
    };
  }


  /**
   * Get author of this component
   */
  public String getAuthor()
  {
    return "TestDummyGenerator by Matthias Ludwig";
  }

  /**
   * Get version of component
   */
  public String getComponentVersion()
  {
    return "0.2";
  }

  /**
   * Get DANUBIA version of component
   */
  public String getDANUBIAVersion()
  {
    return "0.9.1";
  }

  /**
   * Get description of component
   */
  public String getDescription()
  {
    return "This is a test dummy implementation for the ###interfaceName### interface";
  }


	}
###endImportedInterfaces###
