%%% Template fuer TestDummy
###importedInterfaces###
	###fileWriter###
		###outputDir######componentPackagePath###test###fileSeparator######interfaceName###TestDummy.java
	###endFileWriter###

	// ###interfaceName###TestDummy.java generated by Generator at ###theDate###

	package ###componentPackageName###.test;


	import org.glowa.danube.tables.*;
	import org.glowa.danube.simulation.*;
	import org.glowa.danube.space.*;
	import org.glowa.danube.datatypes.*;
	import org.glowa.danube.utilities.*;

	import java.util.*;


	public class ###interfaceName###TestDummy extends org.glowa.danube.testenvironment.AbstractTestModel
		implements ###interfacePackageName###.###interfaceName###
	{
	// PIDs for computation
	private int[] pids = null;


%%% declare export tables
	###publicMethods###
	private ###methodReturnType### ###methodAttribute###Table = null;
	###endPublicMethods###

%%% implement abstract methods from AbstractModel




	public void processInit() throws ComponentInitException
	{

		pids = getModelContext().getAreaMetaData().getPIDArray();
		// Generate export tables
		###publicMethods###
		###methodAttribute###Table = new ###methodReturnType###(getModelContext().getAreaMetaData());
		###endPublicMethods###
	}

	protected void processAbort()
	{
		// Free export tables
		###publicMethods###
		###methodAttribute###Table = null;
		###endPublicMethods###
	}

	public void processGetData( DanubiaCalendar actTime ) throws ModelComputeException
	{
	}

	public void processCompute( DanubiaCalendar actTime ) throws ModelComputeException
	{
	}

	public void processCommit( DanubiaCalendar nextTime ) throws ModelCommitException
	{
		// Actualize export tables
%%%		for (int i=0; i<pids.length; i++)
%%%		{
		###publicMethods###
%%%		###methodAttribute###Table.setValue( pids[ i ], (float) Math.random()*10.0f );
		###endPublicMethods###
%%%		}
	}

%%% implement getter from the interface

	###publicMethods###
    public ###methodReturnType### ###methodName###()
    {
		return ###methodAttribute###Table;
	}
	###endPublicMethods###
	}
###endImportedInterfaces###
